export const config = {
  personName: "Alguien muy especial",
  salutation: "Para {personName}:",
  letterBody: [
    "Hoy quería decirte algo que a veces se queda",
    "en el aire sin encontrar palabras.",
    "",
    "No es un gran discurso ni nada extraordinario,",
    "solo un reconocimiento sencillo y honesto:",
    "",
    "tu presencia trae una calma que",
    "no encuentro en otro lugar.",
    "Los pequeños gestos que tienes",
    "hacen una diferencia enorme en mi día a día.",
    "",
    "Gracias por ser quien eres,",
    "por tu silencio reconfortante",
    "y tu compañía constante.",
    "",
    "Eso es todo. Simplemente,",
    "gracias por existir.",
  ],
  closing: "Un pequeño detalle para alguien enorme en mi corazón.",
  signature: "Con cariño",
  buttonIntro: "Para alguien muy especial",
  buttonLetter: "Hay algo más para ti ♡",
  buttonBouquet: "Guardar este ramo ♡",
  pngFilename: "ramo-para-alguien-especial.png",
}